"""added password to person,removed not null

Revision ID: 34bc9cf26ba0
Revises: e515c9c9a3ab
Create Date: 2025-01-26 15:25:22.348868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34bc9cf26ba0'
down_revision: Union[str, None] = 'e515c9c9a3ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'password_hash')
    # ### end Alembic commands ###
