"""updating datatype to reservation

Revision ID: 4ad7a5109479
Revises: b3d0ecff2728
Create Date: 2025-01-23 12:17:35.487160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ad7a5109479'
down_revision: Union[str, None] = 'b3d0ecff2728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIME(),
               existing_nullable=False)
    op.alter_column('slots', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'end_time',
               existing_type=sa.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('slots', 'start_time',
               existing_type=sa.TIME(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
