"""adding fields to reservation

Revision ID: b3d0ecff2728
Revises: 1d96b6060924
Create Date: 2025-01-23 11:17:40.995238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3d0ecff2728'
down_revision: Union[str, None] = '1d96b6060924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slots', sa.Column('start_time', sa.TIMESTAMP(), nullable=False))
    op.add_column('slots', sa.Column('end_time', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slots', 'end_time')
    op.drop_column('slots', 'start_time')
    # ### end Alembic commands ###
