"""changing ondelete in slots table

Revision ID: df27e3e6462f
Revises: 4ad7a5109479
Create Date: 2025-01-23 12:25:30.930974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df27e3e6462f'
down_revision: Union[str, None] = '4ad7a5109479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('slots_person_id_fkey', 'slots', type_='foreignkey')
    op.create_foreign_key(None, 'slots', 'person', ['person_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'slots', type_='foreignkey')
    op.create_foreign_key('slots_person_id_fkey', 'slots', 'person', ['person_id'], ['id'])
    # ### end Alembic commands ###
