"""empty message

Revision ID: e1e486a2a404
Revises: 3dffd67d2db9
Create Date: 2025-01-16 12:01:21.339816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1e486a2a404'
down_revision: Union[str, None] = '3dffd67d2db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_male', sa.Boolean(), nullable=True))
    op.drop_column('person', 'isMale')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('isMale', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('person', 'is_male')
    # ### end Alembic commands ###
