"""changed datatype as str for time in slots table

Revision ID: e515c9c9a3ab
Revises: df27e3e6462f
Create Date: 2025-01-23 13:15:59.890176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e515c9c9a3ab'
down_revision: Union[str, None] = 'df27e3e6462f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'start_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
    op.alter_column('slots', 'end_time',
               existing_type=postgresql.TIME(),
               type_=sa.String(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('slots', 'end_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=False)
    op.alter_column('slots', 'start_time',
               existing_type=sa.String(length=10),
               type_=postgresql.TIME(),
               existing_nullable=False)
    # ### end Alembic commands ###
